name: DeploymentPipeline

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Install Package
        run: npm install
      - name: Build
        run: -- -m "Deploy React app to GitHub Pages"
      - name: Git Auto Commit
        # You may pin to the exact commit or the version.
        # uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          # Commit message
          commit_message: Published
    
  
