name: DeploymentPipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gh-page-deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Package
        run: npm install
      - name: echo a secret  
        run: |
          echo "${{vars.MY_NAME}} and ${{vars.MY_EMAIL}} and ${{secrets.GH_SECRET}} and ${{github.repository}}"
          echo "here ${{vars}}"
      - name: Build
        env:
          MY_EMAIL: ${{vars.MY_EMAIL}}
          MY_NAME: ${{vars.MY_NAME}}
        run: |
          git config  user.email $MY_EMAIL
          git config  user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{secrets.GH_SECRET}}@github.com/baldazi/react-learn.git
          npm run deploy -- -m "Deploy React app to GitHub Pages"
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Published

