name: DeploymentPipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Package
        run: npm install
      - name: Build
        env:
          MY_EMAIL: secrets.MY_EMAIL
          MY_NAME: secrets.MY_NAME
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{secrets.GH_SECRET}}@github.com/$MY_NAME/react-learn.git
          npm run deploy -- -m "Deploy React app to GitHub Pages"
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Published
